### ISSUE TITLE
AudioFileOpenURL failed

### ISSUE THREAD

**Issue by garria10** [blogmywiki/PyPlay#1]
Trying to run your PyPlay, I get:

Last login: Thu Oct 29 17:53:47 on ttys000
Alans-Air:~ garria10$ cd /Users/garria10/Music/pyth 
Alans-Air:pyth garria10$ python pyplay.py
Fail: AudioFileOpenURL failed
Traceback (most recent call last):
  File "pyplay.py", line 128, in <module>
    trackList.append([trackArray[a],colform(trackArray[a],15),getTrackLength(a),displayDuration(getTrackLength(a)),"status"])
  File "pyplay.py", line 42, in getTrackLength
    bumf = subprocess.check_output(foo, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'afinfo Computers.mp3' returned non-zero exit status 1
Alans-Air:pyth garria10$ 

Any ideas what I'm doing wrong?

**Comment by blogmywiki** [comment]
Hi Alan! It's trying to play a file called Computers.mp3 in the directory where the python script is - I'm guessing you don't have that file! Am about to upload a new version of PyPlay that will make a playlist from any audio files in the folder.
Cheers!
Giles

**Comment by garria10** [comment]
Thanks! It's all very new to me...

**Comment by blogmywiki** [comment]
The new version is there now. Delete the playlist.m3u and pyplay.py files you have, put the new pyplay.py file in the same folder as some audio files, run it from the Terminal command line, and it should make a new playlist of audio files you actually have. Good luck! Let me know if it works.

**Comment by garria10** [comment]
Got a bit further...

No playlist.m3u file found so making you one with these files:

10cc - I'm not in love.mp3
Bartok - Romanian Folk Dances.mp3
Supper's Ready - Genesis.mp3
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
Traceback (most recent call last):
  File "pyplay.py", line 162, in <module>

trackList.append([trackArray[a],colform(newName,20),getTrackLength(a),displayDuration(getTrackLength(a)),"status"])
  File "pyplay.py", line 47, in getTrackLength
    bumf = subprocess.check_output(foo, shell=True)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'afinfo 10cc\\ -\\ I'm\\ not\\
in\\ love.mp3' returned non-zero exit status 2
Alans-Air:pyth garria10$

**Comment by blogmywiki** [comment]
I think it didn't like the apostrophes in the title of the 10cc and Genesis tracks - more debugging needed on my part!

**Comment by blogmywiki** [comment]
Should now be fixed - after a lot of head-scratching! Was quite easy to get it playing audio files with apostrophes in file names, much harder to get it to display the track names nicely. Delete your old pyplay.py and replace with the new code, let me know if it works!

**Comment by garria10** [comment]
still having problem. I tried changing the mp3 files but no joy:
Last login: Fri Oct 30 23:40:16 on ttys000
Alans-Air:~ garria10$ cd /Users/garria10/Music/pyth
Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

Peter Gabriel Here comes the flood.mp3
Ravel - La Valse.mp3
Suppers Ready Genesis.mp3
Fail: AudioFileOpenURL failed
Traceback (most recent call last):
  File "pyplay.py", line 170, in <module>

trackList.append([trackArray[a],colform(newName,20),getTrackLength(a),displayDuration(getTrackLength(a)),"status"])
  File "pyplay.py", line 51, in getTrackLength
    bumf = subprocess.check_output(foo, shell=True)
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'afinfo Peter\\ Gabriel\\ Here\\
comes\\ the\\ flood.mp3' returned non-zero exit status 1
Alans-Air:pyth garria10$

**Comment by blogmywiki** [comment]
There may still be a bug with multiple spaces in filenames - will have a look!

**Comment by blogmywiki** [comment]
New version uploaded with **horrible** kludge to get round problems with multiple spaces - code needs a rewrite really, but see if this works. I've tested it with mp3 files that have the same filenames as yours (different audio though!) and it seems to work. Cheers, G.

**Comment by garria10** [comment]
mixture of sucess and failure. mp3 files with a single word title work, now
mostly it copes with spaces and apostrophes but doesn't like my copy of
'I'm not in  love'...

Last login: Sun Nov  1 11:11:15 on ttys000

Alans-Air:~ garria10$ cd /Users/garria10/Music/pyth

Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

10cc - I'm not in love.mp3

flood.mp3

Supper.mp3

Valse.mp3

Fail: AudioFileOpenURL failed

Traceback (most recent call last):

  File "pyplay.py", line 180, in <module>

trackList.append([trackArray[a],colform(newName,20),getTrackLength(a),displayDuration(getTrackLength(a)),"status"])

  File "pyplay.py", line 52, in getTrackLength

```
bumf = subprocess.check_output(foo, shell=True)
```

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 573, in check_output

```
raise CalledProcessError(retcode, cmd, output=output)
```

subprocess.CalledProcessError: Command 'afinfo 10cc\ -\ I\\'m\ not\ in\
love.mp3' returned non-zero exit status 1

Alans-Air:pyth garria10$

Alans-Air:pyth garria10$ cd /Users/garria10/Music/pyth

Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

flood.mp3

Supper.mp3

Valse.mp3

Welcome to PyPlay!        11:23:20

# Track                         Length  Status  Out time

 1 flood.mp3            4:29

 2 Supper.mp3           22:58

 3 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

Which track would you like to play? q

Alans-Air:pyth garria10$ cd /Users/garria10/Music/pyth

Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

10cc - Life is a Minestrone.mp3

flood.mp3

Supper.mp3

Valse.mp3

Welcome to PyPlay!        11:24:32

# Track                         Length  Status  Out time

 1 10cc - Life is a Min 4:26

 2 flood.mp3            4:29

 3 Supper.mp3           22:58

 4 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

Which track would you like to play? 1

Welcome to PyPlay!        11:24:35

# Track                         Length  Status  Out time

 1 10cc - Life is a Min 4:26 PLAYING 11:29:01

 2 flood.mp3            4:29

 3 Supper.mp3           22:58

 4 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

^C

Welcome to PyPlay!        11:24:40

# Track                         Length  Status  Out time

 1 10cc - Life is a Min 4:26

 2 flood.mp3            4:29

 3 Supper.mp3           22:58

 4 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

Which track would you like to play? q

Alans-Air:pyth garria10$ cd /Users/garria10/Music/pyth

Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

10cc - I´m Mandy,fly me.mp3

10cc - Life is a Minestrone.mp3

flood.mp3

Supper.mp3

Valse.mp3

Welcome to PyPlay!        11:26:15

# Track                         Length  Status  Out time

 1 10cc - I´m Mandy,fl 5:21

 2 10cc - Life is a Min 4:26

 3 flood.mp3            4:29

 4 Supper.mp3           22:58

 5 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

Which track would you like to play? 1

Welcome to PyPlay!        11:26:23

# Track                         Length  Status  Out time

 1 10cc - I´m Mandy,fl 5:21 PLAYING 11:31:45

 2 10cc - Life is a Min 4:26

 3 flood.mp3            4:29

 4 Supper.mp3           22:58

 5 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

q

q

^C

Welcome to PyPlay!        11:26:42

# Track                         Length  Status  Out time

 1 10cc - I´m Mandy,fl 5:21

 2 10cc - Life is a Min 4:26

 3 flood.mp3            4:29

 4 Supper.mp3           22:58

 5 Valse.mp3            13:06

Press ctrl+c to stop playing, q to quit

Which track would you like to play? q

Alans-Air:pyth garria10$ cd /Users/garria10/Music/pyth

Alans-Air:pyth garria10$ python pyplay.py

No playlist.m3u file found so making you one with these files:

10cc - I'm not in love.mp3

10cc - I´m Mandy,fly me.mp3

10cc - Life is a Minestrone.mp3

flood.mp3

Supper.mp3

Valse.mp3

Fail: AudioFileOpenURL failed

Traceback (most recent call last):

  File "pyplay.py", line 180, in <module>

trackList.append([trackArray[a],colform(newName,20),getTrackLength(a),displayDuration(getTrackLength(a)),"status"])

  File "pyplay.py", line 52, in getTrackLength

```
bumf = subprocess.check_output(foo, shell=True)
```

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 573, in check_output

```
raise CalledProcessError(retcode, cmd, output=output)
```

subprocess.CalledProcessError: Command 'afinfo 10cc\ -\ I\\'m\ not\ in\
love.mp3' returned non-zero exit status 1

Alans-Air:pyth garria10$

**Comment by blogmywiki** [comment]
Horrible kludge tweaked - now strips out all multiple backlashes, not just ones before spaces. Hope this works! Of course it would be better if the code didn't put them there in the first place...

**Comment by garria10** [comment]
That seems to have done the trick, I wondered where all the backslashes
came from!
I recall from early days of audio file names that spaces and some other
characters caused problems, hence using underline "_" instead - wouldn't
want to go back to that!

Will be interested to see how this develops...

I hope you are well - how are you doing? heard you were looking for a job?

**Comment by blogmywiki** [comment]
Thanks for your help with this! Probably won't make any progress on it until Christmas holidays now; I have a really great job teaching Computing, very happy.
